# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d7f9e37ccf3d053ac973533f2f4059eb9a7e6c401f6390ca0792b0210065dec9b01c50155bce746ab6e76b81bce55176f3bb0c5cd748725d822d650236b14b

test:
  secret_key_base: 8c9fd547408ebc4c419b38205be5290e38ef2cfbe55f863bdcee3a70b0e64fd7eb1a615deb58319ddfb0ec4333a10603c5cb7b654ae5cd80673ada6eea320b0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
